spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/auto_shop
    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
